### ISSUE TITLE
StopLimit arguments

### ISSUE THREAD

**Issue by eyesuk** [alienbrett/PyAlly#10]
I have tried to get a StopLimit according to the documentation but I am unable to get it working.  Can you please provide insight  into what is the correct format?

See troubleshooting below:

`ally.order.StopLimit()`
TypeError: StopLimit() missing 2 required positional arguments: 'stopOrder' and 'limitOrder

`ally.order.StopLimit()`
TypeError: StopLimit() missing 2 required positional arguments: 'stopOrder' and 'limitOrder

`ally.order.StopLimit(stopOrder(10),limitOrder(9))`
NameError: name 'stopOrder' is not defined

`ally.order.StopLimit(Stop(10),Limit(9))`
NameError: name 'Stop' is not defined

`ally.order.StopLimit(stopOrder=(10),limitOrder=(9))`
TypeError: 'int' object is not subscriptable

`ally.order.StopLimit(stopOrder=10,limitOrder=9)`
TypeError: 'int' object is not subscriptable

`ally.order.StopLimit(10,9)`
TypeError: 'int' object is not subscriptable

**Comment by alienbrett** [comment]
This is a namespace problem. Your 3rd attempt is almost right,
`stopOrder => ally.order.stopOrder`
