### ISSUE TITLE
JSON URL Assembly

### ISSUE THREAD

**Issue by Rob-Valdez** [alienbrett/PyAlly#12]
Thanks for this great package.  In the __init__.py file, line 305, I had to remove the letter "x" from "orderxs" in theURL assembly in order to get it to work. After doing so, I was able to submit orders.  I don't know if others will have that issue as well.

Now for me it looks like the following:

`    # Assemble URL`
`        url = self.endpoints['base']          +\`
`        'accounts/'                     +\`
`        str(account)                    +\`
`        '/orders'                       +\`
`        ('/preview' if preview else '') +\`
`        '.json'`

**Comment by alienbrett** [comment]
Thanks Rob, just merged this
