### ISSUE TITLE
Correction to AcctType for "Buy to Cover" execution

### ISSUE THREAD

**Issue by Rob-Valdez** [alienbrett/PyAlly#13]
This is a really great package.  Thank you.  In the order.py file, line 122, I had to add the letter "t" to "AccTyp" so that it now reads "AcctTyp" to get Buy to Cover execution to work.  I realized the little "t" was missing after reviewing Ally's API docs here: https://www.ally.com/api/invest/documentation/trading/

**Comment by Rob-Valdez** [comment]
I made a pull request for your review for this change.  I haven't contributed before, so apologies if I didn't do anything correctly.

**Comment by alienbrett** [comment]
Thanks Rob- I just merged it
