### ISSUE TITLE
submit_order() got an unexpected keyword argument 'order'

### ISSUE THREAD

**Issue by eyesuk** [alienbrett/PyAlly#17]
Hello,
Got his error after updating to the latest version,  I tried to troubleshoot but have come up empty.
See the screenshot below.  I get this error no matter what order type I try to submit.
![Screen Shot 2020-03-25 at 11 37 01 AM](https://user-images.githubusercontent.com/9576885/77555284-79bb8d00-6e8d-11ea-9b81-9c89af003454.png)

Thanks for your help man

**Comment by alienbrett** [comment]
For now, use 'orderx=...', and this will be fixed in the next release. Sorry for the inconvenience

**Comment by eyesuk** [comment]
Thanks man However, I tried that a few days ago and got a Key Error
![Screen Shot 2020-03-27 at 12 30 04 PM](https://user-images.githubusercontent.com/9576885/77778144-f7ff6700-7026-11ea-81c8-ba61382c4fcf.png)
