### ISSUE TITLE
No module named 'pyximport'

### ISSUE THREAD

**Issue by eyesuk** [alienbrett/PyAlly#18]
Good Morning,
Thanks for the update boss, however it appears that there is an additional bug relating to a missing module named pyximport.  I tried to find reference to this module in the code but I was unable to, although the error persist after commenting it out.  Maybe there is something on my end that I am missing, or I am just not looking int he right place..

![Screen Shot 2020-03-28 at 6 26 03 AM](https://user-images.githubusercontent.com/9576885/77821330-d9997a00-70bf-11ea-946d-6232ff55077d.png)
![Screen Shot 2020-03-28 at 6 25 24 AM](https://user-images.githubusercontent.com/9576885/77821331-d9997a00-70bf-11ea-815a-aad5f621a8bf.png)

Thanks for all your help, on this man I'll make sure to provide some beer money :D I appreciate you and your efforts man

**Comment by alienbrett** [comment]
I'll put this in the Setup.py so this becomes automatic- this is a new dependency to make the code execute faster. Just run
`pip install pyximport`
and you should be good to go.

**Comment by eyesuk** [comment]
Hey man, thanks for your email, I really appreciate it!  to install pyximport I had to use `pip install cython`.  Thanks for all your help man!!!
