### ISSUE TITLE
get_holdings needs account #

### ISSUE THREAD

**Issue by JTraversa** [alienbrett/PyAlly#19]
Though the documentation appears to indicate that an account # is not necessary to execute get_holdings, it appears that the function returns a Keyerror searching for an account value if you do not provide one.  

I am unsure of whether this is an issue with documentation or the wrapper as I haven't looked into ally's documentation on the call as of yet.

**Comment by eyesuk** [comment]
I am able to get my account holdings with the code below 
```
import ally
a = ally.Ally()
h = a.get_holdings()
print(h)
```
The account number must be in your shell startup files along with the APIkeys, but it does work

**Comment by JTraversa** [comment]
Ah, I've hardcoded everything as I'm distributing the application to at least a few others and prompt for input for their Keys. I can just prompt for an account # as well. 

Just was not sure if you could query multiple accounts under a key pair at once by omitting a specific account #.

**Comment by eyesuk** [comment]
> Just was not sure if you could query multiple accounts under a key pair at once by omitting a specific account #

APIkeys are unique to accounts, if you would like to query multiple accounts, you would have to submit a new request with the appropriate keys and acct number for the account you are querying.
