### ISSUE TITLE
fmt_query not defined

### ISSUE THREAD

**Issue by cgar** [alienbrett/PyAlly#20]
o/
Thanks for the project, real clean with great examples.

 I'm working from within PyCharm, env variables set and working. Other functions like a.get_strike_prices() or a.get_exp_dates() working fine. Having an issue with the options search listed on the [Wiki/Options-Contract](https://github.com/alienbrett/PyAlly/wiki/Option-Contracts).

```
import ally

a = ally.Ally()

available_options = a.search_options(
    symbol='SPY',
    query='xdate-eq:20201231', # Mature on 2020-12-31
    fields=['bid','ask'] # 'bid,ask' also works. Function properly formats a list or a string
)

print(available_options)
```

Getting the following error:

```
C:\Dev\options_ally\venv\Scripts\python.exe C:/Dev/options_ally/run.py
Traceback (most recent call last):
    File "C:/Dev/options_ally/run.py", line 7, in
        available_options = a.search_options(
    File "C:\Dev\options_ally\venv\lib\site-packages\ally\option_info.py", line 72, in search_options
        'query':fmt_query,
NameError: name 'fmt_query' is not defined

Process finished with exit code 1
```

When I look at the option_info.py file, I can see fmt_query defined under options_chain but not search_options. Not sure if that's the issue.

Thanks for the help.

**Comment by JTraversa** [comment]
Thats definitely the issue. It looks like the functions were intended to be used together, as options_chain calls search option, but "fmt_" from options_chain wasnt removed from the search_options query.

My assumption is that deleting "fmt_" from the data field in search_options should correct this issue.

**Comment by alienbrett** [comment]
This is merged and will be in the next release
