### ISSUE TITLE
Alphanumeric Account Numbers

### ISSUE THREAD

**Issue by theonewolf** [alienbrett/PyAlly#24]
In the library, there is an assumption that account identifiers are numeric (integer) only.  Accounts can actually have alphabet characters in them.

I am trying to locate canonical documentation about this.

If I have time, I will also submit a PR in to resolve this.

**Comment by alienbrett** [comment]
If you can find documentation about this or a message from the API team, I'll rewrite this to include alphanumeric keys. Until then, I'm gonna leave it as-is. Just curious, is this for an Ally-Invest account, or a savings account?
