### ISSUE TITLE
Account History

### ISSUE THREAD

**Issue by eyesuk** [alienbrett/PyAlly#26]
Hello,
Are you guys able to get Account History, I swore I was able to do this in previous versions, specifically .3.3.  Have anyone of you guys run into this problem?
![Account History Results](https://user-images.githubusercontent.com/9576885/79505997-43dc7500-8003-11ea-8513-c4de53d97572.png)

**Comment by alienbrett** [comment]
Thanks for bringing this to my attention, this is fixed in V0.3.
