### ISSUE TITLE
Sell to Close Error, Similar to Issue #7

### ISSUE THREAD

**Issue by eyesuk** [alienbrett/PyAlly#27]
Hello everyone,
I while trying to submit a market sell order today I got the error below:
> We do not accept Sell Short Against the Box orders online

It appears that the order.Sell(to_open=False) is executing a sell short versus closing position.  Maybe I am missing something tho. See the order construct below:
```
def market_sell(sym,quan):
	mktsell = ally.order.Order(
		timespan = ally.order.Timespan('day'),
		type = ally.order.Sell(to_open=False ),
		price = ally.order.Market(),
		instrument = ally.instrument.Equity(sym),
		quantity = ally.order.Quantity(quan)
	)
	return mktsell
```

Thanks for your help

**Comment by alienbrett** [comment]
Thanks for bringing this up, fixed in V0.3.7
