### ISSUE TITLE
get_quote error when submitting a list of symbols

### ISSUE THREAD

**Issue by replork** [alienbrett/PyAlly#28]
It looks as though some deprecated code was inadvertently left in the get_quote function and returns {} if a list of symbols is used. Deleting lines 241-243 resolves the issue.

  241.    Ensure correctly-typed input
  242.    if not utils.check(symbols):
  243.    return {} 

The error is shown below using t4 of tests.py
Before deletion:
![image](https://user-images.githubusercontent.com/36649598/79610760-2a9cfc80-80c7-11ea-9c30-90af2d821750.png)
After deletion:
![image](https://user-images.githubusercontent.com/36649598/79610966-8e272a00-80c7-11ea-8af6-7d4360bda4be.png)

**Comment by alienbrett** [comment]
Submitting quotes in one format or the other is supported, ie. using a list or using a comma-separated string. However, mixing the two is not supported. If you have an actual fix then I'll merge it, but until then I'm not gonna remove the string check. The goal is to catch unclean requests to save time, and checking some complicated nest of strings and arrays is not ideal. If you want a quote, format it correctly
