### ISSUE TITLE
Issue setting Environment Variables?

### ISSUE THREAD

**Issue by platformmaster9** [alienbrett/PyAlly#4]
Hey alienbrett,

I'm trying to get into API's specifically for Ally and I stumbled onto your python API which looks awesome. Everything is almost running but thought that it would be helpful to know when setting the environment variables, the export ALLY_OATH_TOKEN should be ALLY_OA**U**TH_TOKEN and same thing goes for the oauth secret (on the website the U is missing). Also, when looking at the code for __init__.py there is a repeat of the ALLY_CONSUMER_KEY of which I've attached a picture. Let me know what you think.

![Capture](https://user-images.githubusercontent.com/48224720/70597144-96b9a200-1bb5-11ea-96da-3420595cb9e0.PNG)

**Comment by alienbrett** [comment]
There was a mismatch between the environment params in the code vs in the readme. I have updated the readme, just use ALLY_OA**U**TH_... in the environment. Please let me know if this was not patched through for you yet
