### ISSUE TITLE
in submit  kwargs['order'] = order NameError: name 'kwargs' is not defined

### ISSUE THREAD

**Issue by meullah** [alienbrett/PyAlly#43]
![image](https://user-images.githubusercontent.com/37839632/85062262-9da71a00-b1c1-11ea-94ea-e5f7332424df.png)

on executing code above i get this error:
```

 "C:\Users\Muham\Anaconda3\lib\site-packages\ally\Order\Submit.py", line 147, in submit
    kwargs['order'] = order
NameError: name 'kwargs' is not defined
```

**Comment by alienbrett** [comment]
This was just fixed in today's update. Also, there's a new unit test so that an error like this hopefully doesn't happen again
