### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Stephen-Kp** [alienbrett/PyAlly#44]
Hi,

Great project! I have 2 questions. How can I view or use the response headers? And I didn't see an example for multi-leg options. Is there a way to buy and sell credit/debit spreads, etc.? 

Thanks.

**Comment by alienbrett** [comment]
Right now there's no way to see the response headers yet, and I don't have plans to include. I'm guessing that you want to see the headers for rate limit information, and I'm working on that right now. Rate limit information should be included in an update in the near future.

As far as multileg orders go, I have no plans to implement this in the near future. You can always split up the multi-leg order into sub-orders with the current package. That said, if you have the time and energy to add support for multi-leg orders, feel feel to push your work upstream. I'm sure others would enjoy seeing that functionality

**Comment by Stephen-Kp** [comment]
Thanks! I’ll see if I can figure it out when I get some time.
