### ISSUE TITLE
repeated same limit pricing

### ISSUE THREAD

**Issue by james1627** [alienbrett/PyAlly#45]
I get the same price for different limits on multiple stocks. After the first order is submitted all of the orders keep that price when they are submitted.

**Comment by james1627** [comment]
![image0](https://user-images.githubusercontent.com/33289031/86148530-bddfae80-bac8-11ea-804c-15e2636e2eae.jpeg)

**Comment by james1627** [comment]
This is only after submission because the order still gives me the correct limit.

**Comment by alienbrett** [comment]
Please check again to see if the same problem is still occuring (maybe best to try this after market hours) with the latest V1.0.6.

**Comment by james1627** [comment]
Thanks, I will try it today after the market closes

**Comment by james1627** [comment]
Works now, Thanks
