### ISSUE TITLE
Extended hours support

### ISSUE THREAD

**Issue by mattrobinson3** [alienbrett/PyAlly#48]
Not specific to your wrapper, but in general I've never been able to figure out how to submit extended hours orders?  Do you have any idea?

**Comment by alienbrett** [comment]
I don't think Ally provides this functionality through their API. You can submit orders after-hours for execution during the next trading session, but I haven't really seen any service that offers extended hours trading.

**Comment by mattrobinson3** [comment]
Ok thanks.  Maybe they'll add that ability eventually.  Especially since they support it thru their website, it would be good to support it thru their api also.
