### ISSUE TITLE
Setting Environment Parameters for Windows

### ISSUE THREAD

**Issue by josephouchie** [alienbrett/PyAlly#5]
I am still a rookie programmer, so I do not operate in a Linux environment (I still use windows).  Unsurprisingly, I am unable to export the necessary environment parameters.  Is there a way I can set the 'base', 'request_token', 'user_auth', and 'resource_owner_key' in my algorithm's source code without exporting the tokens to the os environment?

**Comment by alienbrett** [comment]
I would recommend trying to get experience with linux: in my opinion, its much easier to get the code infrastructure and libraries set up in a unix environment.

But if you're using windows, you could store the strings in a text file and read them each time you run your programs.
I'd recommend using JSON, and using the standard json library in python for this task.

Let me know if you have any problems getting the package to work once this is set.

**Comment by josephouchie** [comment]
I was considering using a .BAT file to load the parameters to the OS environment.  What are your thoughts on that?  Also, I needed to download a FIXML library for your wrapper to work (for other users reading this, FIXML is the message protocol necessary to order trades).  I'm not sure if anyone else had this issue, but it is a simple fix that users should be aware of.

**Comment by fny** [comment]
You could also easily do this inside the python script with `os.environ[key] = value`

**Comment by alienbrett** [comment]
There's other resources on setting environment variables, so I'll close this thread
