### ISSUE TITLE
Options Search

### ISSUE THREAD

**Issue by sargun** [alienbrett/PyAlly#50]
I would love to be able to search options in the API. Specifically:

* https://www.ally.com/api/invest/documentation/market-options-search-get-post/
* https://www.ally.com/api/invest/documentation/market-options-strikes-get/
* https://www.ally.com/api/invest/documentation/market-options-expirations-get/

I'm willing to help add it if folks are open.

**Comment by alienbrett** [comment]
These have been added to the latest 1.1.0 release. Please check out [the documentation ](https://alienbrett.github.io/PyAlly/option.html)if you want to become familiar with the features.
