### ISSUE TITLE
order details/status

### ISSUE THREAD

**Issue by granzyme** [alienbrett/PyAlly#51]
Can you provide an example for retrieving details for recent orders, including fill status, side, quantity, price, and symbol. I have tried ally.Ally.orders(), but the response is not comprehensive.

**Comment by alienbrett** [comment]
try examining
`[ str(x) for x in a.orders() ]`

**Comment by granzyme** [comment]
Thank you for your reply. This is what I am able to retrieve per your suggestion:
>> (OType.Order) Side.BuyCover 1 units of "AAPL" TimeInForce.GTC, Limit $250.5

Is PyAlly able to retrieve a more comprehensive response that includes each order's timestamp, fill/cancel/reject status, and id?

**Comment by alienbrett** [comment]
I added some documentation to make this clearer. Please check out [the new section ](https://alienbrett.github.io/PyAlly/trading.html#viewing-open-orders)and let me know if you think any additional documentation would be helpful.
