### ISSUE TITLE
issue getting holdings when there is only 1 asset.

### ISSUE THREAD

**Issue by alphatrades4** [alienbrett/PyAlly#53]
There is a corner case when there is only 1 asset in an account. The code below from holdings.py expects a list in response but for only one asset it doesn't return a list. 

def extract ( self, response ):
		"""Extract certain fields from response
		"""
		response = response.json()['response']
		**holdings** = response['accountholdings']['holding']

		return list( map( Holdings._flatten_holding, holdings ) )

The fix that I am doing locally is this to get over the issue.

def extract ( self, response ):
		"""Extract certain fields from response
		"""
		response = response.json()['response']
		holdings = response['accountholdings']['holding']

		**if not isinstance(holdings, list):
			holdings = [holdings]**

		return list( map( Holdings._flatten_holding, holdings ) )

**Comment by JTraversa** [comment]
Early morning for me but a couple typo'd references later and I've referenced it in PR #54

**Comment by alienbrett** [comment]
Thanks JTraversa, this issue appears fixed and is in the latest release
