### ISSUE TITLE
Add Market API

### ISSUE THREAD

**Issue by fny** [alienbrett/PyAlly#6]
I can add this if you're interested. Also let me know if you need help with anything else (e.g. proper types for holdings info). I was planning on writing something similar!

**Comment by eyesuk** [comment]
That would be awesome!

**Comment by alienbrett** [comment]
I'm working with the API maintainers to understand how this is working. This feature is in active development, but if you can get it working (I have a portion of code I'm working on in api_calls.py), then submit a pull request and I'll gladly merge it

**Comment by alienbrett** [comment]
This is added in V1.0.1. Please reopen an issue if you find problems with the new function
