### ISSUE TITLE
get all quote attributes

### ISSUE THREAD

**Issue by klaypigeon** [alienbrett/PyAlly#61]
Forgive me if I am totally missing something here, I am new to pandas. I see the default is to get all data fields, but I cannot get that to return anything useful

```
>>> quotes = a.quote(symbols=['spy','gLD','F','Ibm'])
>>> quotes
Empty DataFrame
Columns: []
Index: [SPY, F, GLD, IBM]
```

But if I call out individual attributes, no problem. How do I specify to get all fields?
```
>>> quotes = a.quote(symbols=['spy','gLD','F','Ibm'],fields=['bid','ask','last','name','volatility12'])
>>> quotes
           ask     bid  ...                                  name volatility12
symbol                  ...                                                   
F        10.50   10.49  ...                   FORD MOTOR CO. (DE)       0.5766
GLD     173.36  172.91  ...                       SPDR GOLD TRUST       0.2010
SPY     369.45  369.33  ...                SPDR S&P 500 ETF TRUST       0.3403
IBM     119.02  119.01  ...  INTERNATIONAL BUSINESS MACHINES CORP       0.4239

[4 rows x 5 columns]
```

**Comment by alienbrett** [comment]
Ally changed their API so that the upstream no longer has this property. Give me a few days and I can add constants that re-add this feature. For now, just ask `a.quote()` explicitly for the fields you want.

**Comment by klaypigeon** [comment]
Thanks, I thought that might be the case. Not a big deal, more curious than
anything.

**Comment by kcphysics** [comment]
Would this also effect the timesales endpoint?

I am attempting something very similar and am getting a 500.

**Comment by alienbrett** [comment]
> Would this also effect the timesales endpoint?
> 
> I am attempting something very similar and am getting a 500.

Post your code and the exception you're receiving

**Comment by LaikaN57** [comment]
DocFix request sent to Ally.

```
MIME-Version: 1.0
Date: Mon, 7 Jun 2021 04:04:32 -0700
Message-ID: <CALGp1dkGH24Jt6nTAQXYtJMH3SE6+j2wnSaCS9rpg1PHcY=ScA@mail.gmail.com>
Subject: DocFix Request: POST market/ext/quotes
From: Alex Kennedy <alexzanderkennedy@gmail.com>
To: InvestAPI@ally.com
Content-Type: multipart/alternative; boundary="00000000000096aab005c42b0184"

--00000000000096aab005c42b0184
Content-Type: text/plain; charset="UTF-8"

Hello,

It looks like the following statement from the Ally Invest API docs is no
longer true...

"fids [...] By default, all applicable data fields are returned." on
https://www.ally.com/api/invest/documentation/market-ext-quotes-get-post/.

Can you please update this page of the docs to reflect the current API.

Original request and follow up investigation (for reference and community
outreach).
https://github.com/alienbrett/PyAlly/issues/61
https://github.com/alienbrett/PyAlly/issues/61#issuecomment-773372267

Thank you,
Alex Kennedy
```

**Comment by LaikaN57** [comment]
> Ally changed their API so that the upstream no longer has this property. Give me a few days and I can add constants that re-add this feature.

@alienbrett did you ever get around to this? If not, no worries. Just doing issue maintenance.

**Comment by LaikaN57** [comment]
> Post your code and the exception you're receiving

@kcphysics bump

**Comment by LaikaN57** [comment]
> DocFix request sent to Ally.

Received by Ally and under review.

**Comment by LaikaN57** [comment]
Fixed in https://github.com/alienbrett/PyAlly/commit/f1b8ca067f27553354a307a87ca0a46fd35ef9a0
