### ISSUE TITLE
watchlists not functional

### ISSUE THREAD

**Issue by klaypigeon** [alienbrett/PyAlly#63]
Was hoping to draw in a watchlist to run analysis, but I don't think this is working any more. Not complaining, just contributing how I can.

Just to show I am connected...
```
>>> a.quote('intc',fields='last')
         last
symbol       
INTC    58.18
```

```
>>> a.watchlists
<ally.Watchlist.Watchlist object at 0x7ffb6bfaa400>
>>> list(a.watchlists)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/theo/.local/lib/python3.8/site-packages/ally/Watchlist/__init__.py", line 189, in __iter__
    return self._all.__iter__()
  File "/home/theo/.local/lib/python3.8/site-packages/ally/Watchlist/__init__.py", line 175, in _all
    return self._lists
AttributeError: 'Watchlist' object has no attribute '_lists'
```
```
>>> list(a.watchlist['options1'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Ally' object has no attribute 'watchlist'
```

**Comment by LaikaN57** [comment]
Hmm.... I was not able to reproduce the issue. Do you have at least 1 watchlists in your Ally account? Maybe it is a different account number? it would be helpful for you to add logging to `ally.Watchlists.methods.GetWatchlists.extract` to see what the `response` (after json decode) is.

Also your last command should be `list(a.watchlists['options1'])` (with and `s`).

**Comment by LaikaN57** [comment]
@klaypigeon bump

**Comment by LaikaN57** [comment]
@klaypigeon bump

**Comment by klaypigeon** [comment]
Thanks for following up but I went a different route with this using a
different API. You can close this issue.
