### ISSUE TITLE
[Proposal] Proposal for Collaboration

### ISSUE THREAD

**Issue by LaikaN57** [alienbrett/PyAlly#67]
@alienbrett @mm0,

Not sure the best way to go about this request so I will just throw it down here bluntly...

I propose that the three of us join forces on this project. @mm0 has added some great contributions in their own fork and I have since been adding code and documentation quality improvements to their fork as well. I have also been servicing a few issues on this repo.

@alienbrett, in the interest having a better SLA on issues and PRs, would you be opposed to:

1. Merging https://github.com/mm0/PyAlly back into this repo
2. Inviting @mm0 and I as collaborators on this repo?

I propose we setup the following branch protection rule on `master` so that 2 people (author and reviewer) are required to merge a change to master (and publish to PyPI):

![image](https://user-images.githubusercontent.com/206373/114263309-8f68fb00-9999-11eb-8c58-b7e5fa986e64.png)

(@alienbrett, I believe as the repo owner you can still override the review process for your own PRs.)

LMK what you think and/or feedback on what else we should do in the meantime.

**Comment by LaikaN57** [comment]
I started to move some of the documentation URLs/resources over for the https://github.com/mm0/PyAlly fork but after merge I can go cherry pick them out and move it back to this repo.

**Comment by alienbrett** [comment]
I'm not opposed to going down this route, since with classes I haven't been able to commit as much time to the project as it deserves. If @mm0 responds in this thread and consents, I'll go ahead and add you both as collaborators and merge the fork.

**Comment by mm0** [comment]
@alienbrett sounds good, I'd be happy to collaborate on this project along with @LaikaN57

**Comment by LaikaN57** [comment]
Awesome. I was going to open a master to master PR for you but it looks like there is an old one that is already open (https://github.com/alienbrett/PyAlly/pull/57).

**Comment by alienbrett** [comment]
The pull is merged, and you both been invited as collaborators. Message me if you need anything
