### ISSUE TITLE
Timesales

### ISSUE THREAD

**Issue by coalfocks** [alienbrett/PyAlly#8]
A method encapsulating [this](https://www.ally.com/api/invest/documentation/market-timesales-get/) API would be awesome, allowing a user to retrieve a limited historical dataset of a symbol/list of symbols on a given interval.

**Comment by coalfocks** [comment]
Jk made it myself. Let me know how you want me to proceed and we can add it to the repo, if you want

**Comment by eyesuk** [comment]
That’s awesome! Would be very helpful for me

**Comment by alienbrett** [comment]
submit a pull request, and Ill look it over. Thanks for the help

**Comment by alienbrett** [comment]
> 
> 
> Jk made it myself. Let me know how you want me to proceed and we can add it to the repo, if you want

Drop me a link to the repo, and we can get this merged, or create a dependency.

**Comment by alienbrett** [comment]
Merged, this will be in V0.3.1
